sudo: false
language: php
php:
  - 7.0
  - 7.1
install: composer install
script: ./vendor/bin/phpunit
after_success: ./vendor/bin/coveralls -v
matrix:
  fast_finish: true
  allow_failures:
     - php: 7.1
